[package]
name = "echo-server"
version = "0.1.0"
edition = "2021"
authors = [
    "Harry Bairstow <harry@walletconnect.com>"
]
build = "build.rs"

[dependencies]
routerify = "3"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

dotenv = "0.15.0"
envy = "0.4"

build-info = "0.0.27"

redis = { version = "0.21.5", features = [ "tokio-comp"] }

opentelemetry = { version = "0.17.0", features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.10.0", features = ["metrics", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.2"

[build-dependencies]
build-info-build = "0.0.27"